### ISSUE TITLE
Larapack Hook Approved

### ISSUE THREAD

**Issue by marktopper** [tu6ge/voyager-chinese-lang#1]
Greetings and thanks for sending in a hook for Larapack.io.

Your hook has been approved, however I recommend that you tag a version in the Github repository, such as `v1.0.0`.

Feel free to email me at mark@ulties.com for any questions or issues.

Thank you,
Mark

**Comment by tu6ge** [comment]
the tag is pushed ,but it is not update by larapack

**Comment by marktopper** [comment]
Hi @tu6ge.
Seems like on bug on larapack.io, I will look into this soon and get back.
Best, Mark
