### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by myixyt** [tu6ge/voyager-chinese-lang#3]
按照教程安装时候报错 php artisan hook:install chinese-lang  
require.chinese-lang is invalid, it should have a vendor name, a forward slash, and a package name. The vendor and package name can be words separated by -, . or _. The complete name should match "^[a-z0-9]([_.-]?[a-z0-9]+)*/[a-z0-9](([_.]?|-{0,2})[a-z0-9]+)*$".

**Comment by tu6ge** [comment]
安装名非法，已经改了，可以使用刚刚发布的 2.0.0-beta 版本

**Comment by tu6ge** [comment]
请问你的问题解决了吗，解决的话我就关闭 issue 了
